--- #YAML:1.0
name:                Net-TFTPd
version:             0.04
abstract:            Perl extension for Trivial File Transfer Protocol Server
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.3201
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Luigino Masarati <lmasarati@hotmail.com>
